name: ci/cd

on:
  push:
    tags:
      - "v*.*.*"
  pull_request:
    branches:
      - "main"

jobs:
  dockerhub:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: sonastea/chatterbox
      - name: Login to DockerHub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: Build and push to DockerHub
        uses: docker/build-push-action@v5
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

  ec2-prep:
    needs: dockerhub
    runs-on: ubuntu-latest
    steps:
      - name: Pull image and stop container
        uses: appleboy/ssh-action@551964ebda1034f0b5449d74db25c42e371ca1f7
        with:
          host: ${{ secrets.AWS_HOSTNAME }}
          username: ${{ secrets.AWS_USERNAME }}
          key: ${{ secrets.AWS_PRIVATE_KEY }}
          envs: database_url
          script: |
            cd /home/shipper/chatterbox
            docker pull sonastea/chatterbox:latest
            docker stop chatterbox
            docker rm -f chatterbox

  ec2-deployment:
    needs: ec2-prep
    runs-on: ubuntu-latest
    steps:
      - name: Deploy and run docker container
        uses: appleboy/ssh-action@551964ebda1034f0b5449d74db25c42e371ca1f7
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          REDIS_URL: ${{ secrets.REDIS_URL }}
        with:
          host: ${{ secrets.AWS_HOSTNAME }}
          username: ${{ secrets.AWS_USERNAME }}
          key: ${{ secrets.AWS_PRIVATE_KEY }}
          envs: DATABASE_URL, REDIS_URL
          script: |
            docker run -v ~/certs:/opt/chatterbox/certs:ro -e DATABASE_URL=$DATABASE_URL -e REDIS_URL=$REDIS_URL --name chatterbox --restart unless-stopped -d -p 443:8443 -t sonastea/chatterbox:latest
            docker ps
